name: "Minio Client Github Action"
description: "Action for interfacing with the mc CLI"
author: "Joel Howse"
inputs:
  endpoint:
    description: "Endpoint of the S3 server"
    required: true
  access_key:
    description: "Access key credential"
    required: true
  secret_key:
    description: "Secret key credential"
    required: true
  bucket:
    description: "Bucket of the S3 server"
    required: true
  source_file:
    description: "Source file"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    MINIO_ENDPOINT: ${{ inputs.endpoint }}
    MINIO_ACCESS_KEY: ${{ inputs.access_key }}
    MINIO_SECRET_KEY: ${{ inputs.secret_key }}
    MINIO_BUCKET: ${{ inputs.bucket }}
    MINIO_SOURCE_FILE: ${{ inputs.source_file }}
branding:
  icon: "upload-cloud"
  color: "blue"
